/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.concesionaria.guis;

/**
 *
 * @author naely
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaContenidos = new javax.swing.JTable();
        btnGenerarPDF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblReporte = new javax.swing.JLabel();
        lblTipoTramite = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 96, -1));

        tablaContenidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Completo", "Costo", "Tipo de Tramite", "Fecha Tramite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaContenidos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 590, 345));

        btnGenerarPDF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerarPDF.setText("Generar PDF");
        getContentPane().add(btnGenerarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        lblReporte.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblReporte.setForeground(new java.awt.Color(255, 255, 255));
        lblReporte.setText("Reporte ");
        jPanel1.add(lblReporte);
        lblReporte.setBounds(30, 20, 110, 32);

        lblTipoTramite.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoTramite.setText("Tipo de tramite");
        jPanel1.add(lblTipoTramite);
        lblTipoTramite.setBounds(40, 70, 130, 16);

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placas", "Licencias", " " }));
        jPanel1.add(cbxTipo);
        cbxTipo.setBounds(130, 70, 82, 22);

        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrear.setText("Crear");
        jPanel1.add(btnCrear);
        btnCrear.setBounds(220, 70, 72, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 50, 140, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\naely\\Downloads\\Itson\\6to Semestre\\BDAvanzadas\\UC2\\Proyecto Unidad 2\\p2 Licencias\\Concesionaria\\src\\main\\java\\org\\itson\\concesionaria\\multimedia\\REPORTES.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 0, 150, 120);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-13, -4, 650, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblTipoTramite;
    private javax.swing.JTable tablaContenidos;
    // End of variables declaration//GEN-END:variables
}
